# Generated by Django 3.2 on 2026-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='freeze_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
