# Generated by Django 3.2 on 2026-02-16 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_freeze_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledwithdrawal',
            options={'ordering': ['scheduled_for']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scheduledwithdrawal',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledwithdrawal',
            name='scheduled_for',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledwithdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledwithdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_withdrawals', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddIndex(
            model_name='scheduledwithdrawal',
            index=models.Index(fields=['status', 'scheduled_for'], name='wallets_sch_status_a5e7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledwithdrawal',
            index=models.Index(fields=['wallet', 'status'], name='wallets_sch_wallet__37075d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallets_tra_wallet__ec3627_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', '-created_at'], name='wallets_tra_type_0f5774_idx'),
        ),
    ]
