# Generated by Django 3.2 on 2026-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20260216_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledwithdrawal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.AddField(
            model_name='scheduledwithdrawal',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
